### PR TITLE
Move boshrelease to repo root

### PR DESCRIPTION
**Pull request by mrdavidlaing**
Previously the logsearch-for-cloudfoundry boshrelease was stored in `<repo-root>/logsearch-for-cloudfoundry-boshrelease` which makes publishing to bosh.io difficult.

This PR pulls the content of `logsearch-for-cloudfoundry-boshrelease` into the <repo-root>.

The logsearch-filter content that was in the <repo-root> has moved to `src/logsearch-config`

NB!  We recommend that you create a fresh clone of this repo to prevent old folders lying around.

```
git clone https://github.com/logsearch/logsearch-for-cloudfoundry.git
cd logsearch-for-cloudfoundry
git submodule init
git submodule update
```

### CODE REVIEW

**Comment by emirozer** [comment]
@mrdavidlaing Sorry for bothering you but i wanted to ask you something, after this change the logsearch-for-cloudfoundry-boshrelease repo is completely removed (at least thats my understanding)

but on the logsearch-for-cloudfoundry repo there is a refarral,

https://github.com/cloudfoundry-community/logsearch-boshworkspace/blob/master/deployments/logsearch-aws-vpc.yml

How can i find a work around, any ideas?

Thank you !

**Comment by mrdavidlaing** [comment]
@emirozer - all the bosh release files exist, just in the root, not under the `logsearch-for-cloudfoundry-boshrelease/` subfolder

I suspect you will just need to change / remove the `path` argument - https://github.com/cloudfoundry-community/logsearch-boshworkspace/blob/master/deployments/logsearch-aws-vpc.yml#L11

**Comment by RaphaelAudet** [comment]
@mrdavidlaing (I'm working with @emirozer) if we remove the ```path```  argument, bosh will look for a release folder at the root of the repo. Unfortunately even the latest version (v7) still has logsearch-for-cloudfoundry-boshrelease within the code and doesn't have a release folder.  Can a new version of logsearch-for-cloudfoundry be released to match this ?

**Comment by mrdavidlaing** [comment]
@RaphaelAudet - can you not just use the master branch?

**Comment by RaphaelAudet** [comment]
@mrdavidlaing  actually I used the commit ref in the deployment manifest but would't it be "cleaner" ?

I would like to submit a fixed deployment-manifest for https://github.com/cloudfoundry-community/logsearch-boshworkspace/blob/master/deployments/logsearch-aws-vpc.yml#L9 and I think a version would make it easier to understand for newcomers (since the bosh's current doc specifies that a version is required).

**Comment by mrdavidlaing** [comment]
@RaphaelAudet I've tagged master with [`v7.5`](https://github.com/logsearch/logsearch-for-cloudfoundry/tree/v7.5)

**Pull request merged**
