### PR TITLE
Haproxy logs index name fix

### PR DESCRIPTION
**Pull request by hannayurkevich**
We parse `haproxy` logs but don't store them into `platform` index. So by default they appear in `unparsed`.

Because `haproxy` logs are tagged as `haproxy` (see https://github.com/logsearch/logsearch-boshrelease/blob/develop/src/logsearch-config/src/logstash-filters/snippets/haproxy.conf) we can use this tag to distinguish appropriate index name (see my commits).

### CODE REVIEW

**Comment by cromega** [comment]
@hannayurkevich: I'm glad you provided some rules for parsing haproxy logs. However, I would love to see some test coverage for the new snippet.

**Comment by hannayurkevich** [comment]
@cromega: It looks like there is some problem with test running script.

I'm starting https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/src/logsearch-config/bin/test and get the following:

`mkdir -p target`
`rm -rf target/*`
`===> Building ...`
`ERB src/logstash-filters/elasticsearch-template.json.erb -> target/elasticsearch-template.json`
`ERB src/logstash-filters/default.conf.erb -> target/logstash-filters-default.conf`
`===> Artifacts:`
`target`
`target/logstash-filters-default.conf`
`target/elasticsearch-template.json`
`target/kibana4-dashboards.json`
`===> Testing ...`
` vendor/logstash/bin/rspec $(find test -name *spec.rb)`
`sh: 1: vendor/logstash/bin/rspec: not found`
`rake aborted!`
`Command failed with status (127): [ vendor/logstash/bin/rspec $(find test -na...]`
`/home/ubuntu/elk/logsearch-for-cloudfoundry/src/logsearch-config/Rakefile:23:in block in <top (required)>'`
`/home/ubuntu/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in eval'`
`/home/ubuntu/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in <main>'`
`Tasks: TOP => test`
`(See full trace by running task with --trace)`

When I open `https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/src/logsearch-config/Rakefile` and look at `test` task I see reference to non-existing path `vendor/logstash/bin/rspec`.

Could you please double-check that the script is correct. And if so share the way of starting tests with me.
Otherwise I'm unable to check my test for `haproxy`.

Thanks in advance.

**Comment by cromega** [comment]
@hannayurkevich: 
```sh
$ cd src/logsearch-config
bin/install-dependencies
```

The tests in this repo are way outdated, they are missing most of the the test plumbing we have done in logsearch-boshrelease recently. Do not spend too much time on creating a very thorough test. Just add a case which checks if some basic fields are extracted from a haproxy log.

Thanks!

**Comment by cromega** [comment]
@hannayurkevich: haproxy log parsing is implemented in logsearch-boshrelease.https://github.com/logsearch/logsearch-boshrelease/blob/develop/src/logsearch-config/src/logstash-filters/snippets/haproxy.conf

if you want to fix something in it please issue a PR for that repo, thanks.

That repo also has up-to-date tests.

**Comment by hannayurkevich** [comment]
@cromega: Hm, you are right parsing rules are defined in **logsearch-boshrelease** project. But **logsearch-for-cloudfoundry** filters don't have any processing of haproxy and as the result haproxy logs go to `unparsed` index. It looks like not really expected behaviour. What do you think?

**Pull request closed without merging**
