### PR TITLE
Dont try to geoip when remote_addr == "-"

### PR DESCRIPTION
**Pull request by simonjohansson**
This can happen if you dont use HAProxy as LB,
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/NMLZERUP4PCO2OTYRBE4E3MUKSO6ELMD/

and produces massive log outputs that make logstash fill up the disk in the middle of the night..

### CODE REVIEW

**Comment by simonjohansson** [comment]
Oh, just noticed that we have other nasty values in x_forwarded_for, namely "unknown".
I will alter the PR to match remote_addr against a regexp.

**Comment by mrdavidlaing** [comment]
@simonjohansson - is this ready for merging?

**Comment by simonjohansson** [comment]
@mrdavidlaing yeah, I would say so. I run the latest commit in our env right now without any issues.

**Comment by simonjohansson** [comment]
Danke. :)

**Pull request merged**
