### PR TITLE
Deployment process documentation

### PR DESCRIPTION
**Pull request by bonzofenix**

### CODE REVIEW

**Comment by bonzofenix** [comment]
I just saw some doc within the release, will work on re write this. Please hold the merge.

**Comment by bonzofenix** [comment]
@mrdavidlaing this PR is ready now IMO. You can check out how documentation looks on [our fork]( https://github.com/compozed/logsearch-boshrelease)

**Comment by mrdavidlaing** [comment]
@bonzofenix - thanks!

2 requests.

1.  Could you add a link from the "root" README to the bosh-release README please.  Something like: `To install, please use the logsearch-for-cloudfoundry-boshrelease, documented here`
2.  Could you ask Anthony Lee to forward me a signed CLA - https://github.com/logsearch/licensing/

**Comment by bonzofenix** [comment]
@mrdavidlaing let me know if you want any other change before merging!

**Pull request merged**
